version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:latest
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: fp_unit
          POSTGRES_DB: fp_unit
          POSTGRES_PASSWORD: fp_unit
    steps:
      - checkout
      - restore_cache:
          name: Restore cached dependencies
          keys:
            - maven3-{{ checksum "pom.xml" }}
      - run:
          name: Build (and run tests)
          command: mvn clean install
      - save_cache:
          name: Cache Maven dependencies
          key: maven3-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

  deploy:
    docker:
      - image: circleci/openjdk:latest
    steps:
      - checkout
      - restore_cache:
          name: Restore cached dependencies
          keys:
            - maven3-{{ checksum "pom.xml" }}
      #- run:
      #    name: Import gpg key
      #    command: echo $GPG_KEY_BASE64 | base64 --decode | gpg --yes --batch --import
      - run:
          name: "Setting version"
          command: |
            sudo apt-get install libxml2-utils
            export GIT_COMMIT_HASH=$(git log -n 1 --pretty=format:'%h')
            export GIT_COMMIT_DATE=$(git log -1 --pretty='%ad' --date=format:'%Y%m%d%H%M%S')
            export REVISION=$(xmllint --xpath '/*[local-name()="project"]//*[local-name()="revision"]/text()' pom.xml)
            export VERSION=${REVISION}_${GIT_COMMIT_DATE}_${GIT_COMMIT_HASH}
            echo "Setting version $VERSION"
            mvn versions:set -DnewVersion="$VERSION"
            mvn versions:commit
      - run:
          name: Deploy to Github Package Registry
          command: "mvn --settings .circleci/maven-settings.xml deploy -PpublishGithub -DskipTests=true"


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
#      - deploy:
#          context: familie-ci
#          requires:
#            - build
#          filters:
#            branches:
#              only: feature/TFP-563
